
name: Style R scripts and Rmd notebooks

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "style"
  style:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:4.2

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        # What branch to commit to: the one from the pull request
        with:
          ref: ${{ github.head_ref }}

      - name: Install packages
        run: Rscript -e "install.packages('styler')"

      - name: Get all changed R or Rmd files
        id: changed-files-R
        uses: tj-actions/changed-files@v37
        with:
          files_R: |
            R:
              - 'Rmd$'
              - '.R$'

      - name: List R or Rmd files that have changed
        if: steps.changed-files-R.outputs.test_any_changed == 'true'
        run: |
          echo "One or more R files has changed"
          echo "List all the files that have changed: ${{ steps.changed-files-R.outputs.test_all_changed_files }}"

      - name: Run styler on R or Rmd files that have changed
        if: steps.changed-files-R.outputs.test_any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files-R.outputs.all_changed_files }}; do
            Rscript -e "styler::style_file(file, recursive = TRUE, full.names = TRUE));warnings()"
          done

      - name: Configure Git repository
        run: |
          git config --global --add safe.directory /__w/AutoGVP/AutoGVP

      - name: Commit style changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply code style changes
          